# Generated by Django 4.2.5 on 2023-10-30 09:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('updated_at', models.DateField(auto_created=True)),
                ('created_at', models.DateField(auto_created=True)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('todo_title', models.CharField(max_length=200)),
                ('todo_description', models.TextField()),
                ('is_done', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
